<?php
/*
 * SPDX-License-Identifier: GPL-3.0-or-later
 * Copyright (C) 2026 Bijstaan
 */
/**
 * Whitelabel — GLPI, wearing your name instead of its own.
 *
 * An MSP hands this interface to its customers, and "GLPI" means nothing to
 * them. It is not a vanity exercise: a helpdesk that announces a product the
 * user has never heard of, in a browser tab that says GLPI, above a logo that
 * is not yours, reads as somebody else's system that you happen to be typing
 * into.
 *
 * Everything here works by the mechanisms GLPI already has rather than by
 * editing core, because a whitelabel that has to be reapplied after every
 * upgrade is a whitelabel that will be wrong within a month:
 *
 *  - **The name** is `$CFG_GLPI['app_name']`, which core already threads
 *    through page titles, notification footers and the 2FA enrolment label.
 *    One assignment, and three surfaces follow.
 *  - **The logos** are CSS custom properties (`--glpi-logo-*`). Overriding
 *    those covers the sidebar, its collapsed form, the login card and both
 *    light and dark themes, without this plugin knowing where any of them are
 *    rendered.
 *  - **The favicon** is a `<link>` core writes *last*, so it has to be
 *    replaced in the browser rather than merely added to.
 *  - **The remaining literals** — the copyright line, the name of the internal
 *    authentication source — are text in core templates, reachable only from
 *    the page. Those are rewritten by selector, never by searching the page for
 *    the word "GLPI", which would eventually rewrite somebody's ticket.
 */

use Glpi\Http\Firewall;
use Glpi\Plugin\Hooks;
use GlpiPlugin\Whitelabel\Settings;

define('PLUGIN_WHITELABEL_VERSION', '0.1.0');
define('PLUGIN_WHITELABEL_MIN_GLPI', '11.0');

define('PLUGIN_WHITELABEL_CONFIG_CONTEXT', 'plugin:whitelabel');

function plugin_init_whitelabel()
{
    global $PLUGIN_HOOKS, $CFG_GLPI;

    $PLUGIN_HOOKS['csrf_compliant']['whitelabel'] = true;
    $PLUGIN_HOOKS['config_page']['whitelabel']    = 'front/config.php';

    /**
     * The two endpoints that must answer before anybody has logged in.
     *
     * GLPI 11 routes every plugin script through its firewall, and the default
     * for a legacy script is "must be authenticated". That is the right default
     * and it is wrong for these two: the login page needs the logo and the
     * stylesheet that names it, and by definition nobody has authenticated yet.
     *
     * Core marks its own `/front/css.php` the same way, for the same stated
     * reason. Without this the browser requests a stylesheet, GLPI answers with
     * an access-denied *page*, and — because that handling tears the session
     * down — every subsequent page reports that the session has expired. The
     * symptom is spectacular and points nowhere near the cause.
     *
     * Neither endpoint reads the session or the database beyond this plugin's
     * own settings, and both serve only what is already on the login page.
     */
    foreach (['#^/front/style\.php#', '#^/front/asset\.php#'] as $public) {
        Firewall::addPluginStrategyForLegacyScripts(
            'whitelabel',
            $public,
            Firewall::STRATEGY_NO_CHECK
        );
    }

    // The single most valuable line in the plugin. Core reads app_name for the
    // <title> of every page, for the "Automatically generated by %s" footer on
    // every notification it sends, and for the label a 2FA authenticator app
    // stores against the account. Setting it here, before anything renders,
    // rebrands all three without a template being touched.
    $name = Settings::get('name');
    if ($name !== '') {
        $CFG_GLPI['app_name'] = $name;
    }

    // Both interfaces and the login page. A whitelabel that stops at the
    // technician view has missed the people it was for.
    foreach (
        [
            [Hooks::ADD_CSS, Hooks::ADD_JAVASCRIPT, Hooks::ADD_HEADER_TAG],
            [
                Hooks::ADD_CSS_ANONYMOUS_PAGE,
                Hooks::ADD_JAVASCRIPT_ANONYMOUS_PAGE,
                Hooks::ADD_HEADER_TAG_ANONYMOUS_PAGE,
            ],
        ] as [$css_hook, $js_hook, $tag_hook]
    ) {
        $PLUGIN_HOOKS[$css_hook]['whitelabel'] = ['css/whitelabel.css'];
        $PLUGIN_HOOKS[$js_hook]['whitelabel']  = ['js/whitelabel.js'];

        // The generated half, as a <link> rather than a file, because what it
        // contains depends on configuration and a plugin directory is not
        // somewhere to be writing files at runtime — plenty of installations
        // mount it read-only, and rightly.
        $PLUGIN_HOOKS[$tag_hook]['whitelabel'] = Settings::headerTags();
    }
}

function plugin_version_whitelabel()
{
    return [
        'name'         => 'Whitelabel',
        'version'      => PLUGIN_WHITELABEL_VERSION,
        'author'       => 'Bijstaan',
        'license'      => 'GPL-3.0-or-later',
        'homepage'     => 'https://github.com/bijstaan/glpi-whitelabel',
        'requirements' => ['glpi' => ['min' => PLUGIN_WHITELABEL_MIN_GLPI]],
    ];
}

function plugin_whitelabel_check_prerequisites()
{
    return true;
}

function plugin_whitelabel_check_config($verbose = false)
{
    return true;
}
