<?php
/*
 * SPDX-License-Identifier: GPL-3.0-or-later
 * Copyright (C) 2026 Bijstaan
 */

namespace GlpiPlugin\Whitelabel;


/**
 * The generated stylesheet.
 *
 * Almost all of the visual half of a whitelabel is four CSS custom properties.
 * Core declares `--glpi-logo-light`, `--glpi-logo-dark`, their `-reduced`
 * variants for the collapsed sidebar and their `-login` variants for the
 * card on the login page, then uses them wherever a logo appears. Overriding
 * them on `:root` reaches every one of those without this plugin knowing which
 * template renders what, and — because they are properties rather than rules —
 * without out-competing core on specificity.
 *
 * Only what has been uploaded is emitted. A half-configured plugin should leave
 * the rest of GLPI looking like GLPI rather than like a broken version of it.
 */
final class Brand
{
    public static function css(): string
    {
        $settings = Settings::all();
        $lines    = [
            '/* Generated by the whitelabel plugin. */',
        ];

        $vars = [];

        $logo    = self::url('logo');
        $reduced = self::url('logo_reduced');
        $login   = self::url('logo_login');

        // Core already keeps a `-light` and a `-dark` of each of these and
        // picks between them by palette, so a second upload is all it takes.
        // Where there is no dark file the light one is used for both, which is
        // right far more often than not: plenty of logos read on either ground,
        // and inverting one that does not is a guess that produces a grey smear
        // out of anything with more than one colour in it.
        //
        // Note which way round core has it. `--glpi-logo-light` is the file
        // core ships as `logo-GLPI-100-*white*.png` — the name describes the
        // ink, not the background, so `-light` is the logo *for* the dark
        // palette. Reading it the other way puts each file on the ground it
        // cannot be seen against, and it looks deliberate.
        $pairs = [
            ''         => [$logo,    self::url('logo_dark')],
            '-reduced' => [$reduced, self::url('logo_reduced_dark')],
            '-login'   => [$login,   self::url('logo_login_dark')],
        ];

        // The login card falls back to the main logo, because a site that
        // uploaded one logo meant it to be used.
        if ($pairs['-login'][0] === '') {
            $pairs['-login'] = [$logo, self::url('logo_dark')];
        }

        foreach ($pairs as $suffix => [$forDark, $forLight]) {
            if ($forDark === '') {
                continue;
            }

            // `--glpi-logo-light-*` is used on the dark palette and vice versa;
            // the primary upload is the one drawn on GLPI's default light
            // ground, so it is the `-dark` property.
            $vars["--glpi-logo-dark$suffix"]  = $forDark;
            $vars["--glpi-logo-light$suffix"] = $forLight !== '' ? $forLight : $forDark;
        }

        if ($logo !== '') {
            $vars['--glpi-logo'] = $logo;
        }

        if ($reduced !== '') {
            $vars['--glpi-logo-reduced'] = $reduced;
        }

        if ($vars !== []) {
            // `:root:root`, not `:root`.
            //
            // Core declares these same properties on `:root`, and this
            // stylesheet is injected into the head *before* core's — plugins
            // get their header tags rendered above the core CSS links, and
            // there is no hook that puts them after. Two declarations of equal
            // specificity means the later one wins, which would be core's, and
            // the logo would never change.
            //
            // Repeating the selector doubles its specificity and settles it
            // without `!important`, which is worth avoiding here: these are
            // custom properties a site may well want to override again in the
            // per-entity custom CSS that GLPI already provides.
            $lines[] = ':root:root {';
            foreach ($vars as $name => $url) {
                $lines[] = sprintf('    %s: url("%s");', $name, $url);
            }
            $lines[] = '}';
        }

        // The About dialog renders an <img> rather than a background, so the
        // custom properties do not reach it. `content` on a replaced element
        // swaps the image itself, which every current engine supports and which
        // degrades to "the old logo, in a dialog nobody opens" where it does
        // not.
        if ($logo !== '') {
            // `!important` here and only here: core writes the size as a
            // `style` attribute on the element, and an attribute beats any
            // selector. This is the one place where there is nothing else to
            // outrank it with.
            $lines[] = '.modal-body img[title="GLPI Logo"] {';
            $lines[] = sprintf('    content: url("%s");', $logo);
            $lines[] = '    max-width: 160px !important;';
            $lines[] = '    height: auto !important;';
            $lines[] = '}';
        }

        // ------------------------------------------------- the first paint
        //
        // The JavaScript that follows the system theme cannot be first. It is a
        // separate file, and by the time the browser has fetched it the
        // stylesheets are already parsed and the page ground has been painted —
        // white, briefly, at whatever brightness the monitor is set to. That is
        // the flash this closes.
        //
        // A stylesheet has no such delay: this file is a <link> in the head and
        // `prefers-color-scheme` needs nothing from JavaScript to answer. So
        // the handful of variables that decide what the page *is coloured*
        // are set here, under the media query, and the script that follows
        // still does the complete palette swap a moment later.
        //
        // Deliberately not the whole dark palette. Restating three hundred
        // declarations from core would be a copy that goes stale on the next
        // GLPI release; these are the four that are the difference between a
        // dark page and a white one, and they are copied verbatim from
        // css/includes/_palette_dark.scss.
        if ((int) $settings['theme_follow_system'] === 1) {
            $dark = Settings::darkVariables();

            if ($dark !== []) {
                // `:not([data-glpi-theme-dark="1"])` on every selector, so the
                // whole block switches itself off the instant the script sets
                // that attribute and core's own palette takes over. It is a
                // stand-in for the time before the script runs, not a second
                // opinion about colour — and because both are built from the
                // same source, the handover is invisible.
                $lines[] = '@media (prefers-color-scheme: dark) {';
                // `:root:root` for the same reason as above — this file is
                // injected before core's, and equal specificity would lose.
                $lines[] = '    :root:root:not([data-glpi-theme-dark="1"]) {';

                foreach ($dark as $property => $value) {
                    $lines[] = sprintf('        %s: %s;', $property, $value);
                }

                $lines[] = '    }';

                // The variables alone are not enough for the very first paint:
                // nothing has read them yet when the browser fills the canvas,
                // so the viewport stays white until an element carries a
                // background of its own.
                $ground = $dark['--tblr-body-bg'] ?? '#000';
                $ink    = $dark['--tblr-body-color'] ?? '#e6e6e6';

                $lines[] = '    html:not([data-glpi-theme-dark="1"]),';
                $lines[] = '    html:not([data-glpi-theme-dark="1"]) body {';
                $lines[] = sprintf('        background-color: %s;', $ground);
                $lines[] = sprintf('        color: %s;', $ink);
                $lines[] = '    }';
                $lines[] = '}';
            }
        }

        if ((int) $settings['hide_credit'] === 1) {
            // One selector covers both places core renders it: the login page
            // footer and the About dialog. See Html::getCopyrightMessage().
            $lines[] = 'a.copyright { display: none !important; }';
        }

        return implode("\n", $lines) . "\n";
    }

    private static function url(string $name): string
    {
        if (!Assets::has($name)) {
            return '';
        }

        return \Html::getPrefixedUrl('/plugins/whitelabel')
            . '/front/asset.php?name=' . rawurlencode($name)
            . '&v=' . (int) Settings::get('revision');
    }
}
